### ISSUE TITLE
Plex DVR에서 사용할 때 channel id 부분에 있는 "&" 문자 때문에 제대로 읽어드리지 못합니다.

### ISSUE THREAD

**Issue by iluvcrong** [epg2xml/epg2xml#1]
Plex DVR 에서 epg xml 파일을 읽어드릴 때 channel id가 있는 경우 다음과 같은 오류를 발생시킵니다.

/epg2xml/xmltv.xml:551: parser error : xmlParseEntityRef: no name
  <channel id="케이블 JTBC GOLF & SPORTS.daum">
                                    ^
xmltv.xml 내에서 "&" 문자를 "&amp;"로 바꾸니 정상적으로 불러옵니다.
출력하실 때 channel id 에 포함된 "&"를 "&amp;"로 바꾸면 해결 될까요?

**Comment by wiserain** [comment]
문제가 되는 채널만 포함해서 설정 epg2xml.json 파일 내용을 같이 첨부해주세요.

**Comment by iluvcrong** [comment]
제가 테스트 해 본 것은 "홈&쇼핑"과 "JTBC GOLF & SPORTS" 2개 채널입니다.

ServiceId를 이용해서 xmltv에서 channel id를 생성하는 것 같은데요. 
"&" 문자가 들어가면 Plex DVR에서 직접 읽어드리지 못하는 것 같습니다.

Tvheadend에서 바로 불러올 때는 문제없습니다. 
Tvheadend를 경유해도(http://tvheadend:9981/xmltv/channels) 문제 없습니다.
Plex DVR에서 직접 xmltv를 불러올 때만 오류가 발생합니다.

[epg2xml_error.json.zip](https://github.com/epg2xml/epg2xml/files/6096380/epg2xml_error.json.zip)

**Comment by wiserain** [comment]
네 `ID_FORMAT`을 이럴때 쓰면 됩니다. GLOBAL에서 기본값이 다음과 같고 `"ID_FORMAT": "{ServiceId}.{Source.lower()}"` 모든 제공자에 적용되며 대부분 문제가 없지만 DAUM의 ServiceId 값들만 non-ascii에 특수문자가 있어서 문제가 될 수 있습니다.

GLOBAL로 적용되는 ID_FORMAT을 아래와 같이 오버라이드 해보세요.
```json
  "DAUM": {
    "ID_FORMAT": "{No}.{Source.lower()}",
    "MY_CHANNELS": [
      { "Name": "홈&쇼핑", "ServiceId": "케이블 홈&쇼핑", "Category": "케이블" },
      { "Name": "JTBC GOLF & SPORTS", "ServiceId": "케이블 JTBC GOLF & SPORTS", "Category": "케이블" }       
    ]
```

**Comment by iluvcrong** [comment]
ID_FORMAT에서 &를 &amp;로 replace 함수를 이용해서 변환해 보려고 했는데, 이건 안되더라구요.
우선 Id 항목을 문제가 되는 채널에만 추가해서 해결했습니다~

```json
  "DAUM": {
    "MY_CHANNELS": [
      { "Name": "홈&쇼핑", "ServiceId": "케이블 홈&쇼핑", "Category": "케이블", "Id": "홈&amp;쇼핑" },
      { "Name": "JTBC GOLF & SPORTS", "ServiceId": "케이블 JTBC GOLF & SPORTS", "Category": "케이블", "Id": "케이블 JTBC GOLF &amp; SPORTS" }       
    ]
  },
```

**Comment by wiserain** [comment]
Id 개별 지정안해도 & 문자 escape하게 했습니다. https://github.com/epg2xml/epg2xml/commit/6a4e9505e88aa69a7988c6539d8549464f51700d

**Comment by iluvcrong** [comment]
감사합니다~
이슈는 닫겠습니다~
