### ISSUE TITLE
Channel.json에 LG 채널 아이디가 사라졌습니다

### ISSUE THREAD

**Issue by wowwoo** [epg2xml/epg2xml#16]
2022/06/11 08:30:02 WARNING  PROV     145: [LG   ] 'ServiceId' Not in Servicee: {'Name': '애니플러스', 'No': '178', 'ServiceId': '699', 'Category': '애니/키즈'}

이런 로그가 찍혀 Channel.json을 확인해보니

  "LG": {
    "UPDATED": "2022-06-10T08:31:02.069396",
    "TOTAL": 0,
    "CHANNELS": []
  },

이렇게 LG 채널 아이디를 안갖고 오는 것 같습니다
홈페이지가 변경이 된건지 이유는 모르겠으나
다른 소스로 변경해서 EPG 갱신엔 문제가 없으나
보고드립니다

언제나 잘 사용하고 있습니다

감사합니다

**Comment by epg2xml** [comment]
버전 확인하시고 업그레이드 해보세요.

**Comment by wowwoo** [comment]
> 버전 확인하시고 업그레이드 해보세요. v2.2.0에서 수정했습니다.

넵 감사합니다
