### ISSUE TITLE
EPG를 가져오지 못합니다...

### ISSUE THREAD

**Issue by HoonE122** [epg2xml/epg2xml#17]
epg2xml.json 파일이 제대로 작성된게 맞을까요?

![epg](https://user-images.githubusercontent.com/83511237/177375596-9322b862-a5dc-4c64-96b8-0740f8691e6b.png)

**Comment by epg2xml** [comment]
눈으로 보기에 문제 없어보입니다. 안되면 로그를 확인하세요.
