### ISSUE TITLE
실행 3번에서 다음 채널 가져올 때 에러가 발생합니다.

### ISSUE THREAD

**Issue by Taemni** [epg2xml/epg2xml#18]
![주석 2022-08-22 023924](https://user-images.githubusercontent.com/48712000/185803872-71bbe558-8c8e-4ea5-8548-2eaa9f5090e1.png)

확인해 봐야 할 부분이 있을까요?

설치는 아래 커맨드를 썼습니다.
pip install "epg2xml[lxml] @ git+https://github.com/epg2xml/epg2xml.git@"

**Comment by epg2xml** [comment]
다음 사이트 차단되었을 가능성이 높습니다. 같은 IP에서 [링크](https://search.daum.net/search?DA=B3T&w=tot&rtmaxcoll=B3T&q=%EC%A7%80%EC%83%81%ED%8C%8C) 접속 되는지 테스트 해보시길 바랍니다.

**Comment by Taemni** [comment]
> 다음 사이트 차단되었을 가능성이 높습니다. 같은 IP에서 [링크](https://search.daum.net/search?DA=B3T&w=tot&rtmaxcoll=B3T&q=%EC%A7%80%EC%83%81%ED%8C%8C) 접속 되는지 테스트 해보시길 바랍니다.
![주석 2022-08-22 145542](https://user-images.githubusercontent.com/48712000/185849139-78dcfeb9-b95f-4e2e-9aa9-54b811a37b85.png)
정상 접속됩니다.

**Comment by epg2xml** [comment]
원래 차단되어도 페이지는 줍니다. html 파일을 열어서 해당 `div` 블록이 있나 확인해 봐야 할 것 같네요.

**Comment by Taemni** [comment]
> 원래 차단되어도 페이지는 줍니다. html 파일을 열어서 해당 `div` 블록이 있나 확인해 봐야 할 것 같네요.
[daum.zip](https://github.com/epg2xml/epg2xml/files/9395200/daum.zip)

당연히 열어서 확인했습니다. response 결과 첨부할게요.

**Comment by epg2xml** [comment]
차단 문제는 아닌 것 같습니다. lxml bs4 버전 좀 알려주세요.

**Comment by Taemni** [comment]
아이고.. 해결됐습니다. 죄송합니다 (__)
버전 말씀하셔서 확인해 보니 lxml == 4.8.0이고 beautifulsoup4가 4.6.0이었습니다.
beautifulsoup4==4.11.1로 업데이트하니 정상 작동되네요.
