### ISSUE TITLE
Channel.json LG 항목의 채널명 이상

### ISSUE THREAD

**Issue by ayodia1** [epg2xml/epg2xml#20]
사용버젼: v2.2.0

우선 덕분에 감사히 잘 사용하고 있다고 말씀드리고 싶습니다. 

업그레이드 된걸 이제 알고 오늘 설치해서 사용해 봤습니다만, 문제가 있네요.

아래와 같이 channel.json파일의 LG쪽 항목에서 channel name에 No 항목이 딸려들어가 있습니다.

예를 들면 "KBS조이" 이어야 하는데 "KBS조이[1]"로 들어가 있습니다. 당연한 이야기이지만, 채널명이 달라서 해당 채널들의 EPG 검색이 IPTV app들에서 안됩니다.

 "LG": {
    "UPDATED": "2022-09-10T02:23:56.472993",
    "TOTAL": 349,
    "CHANNELS": [
      { "Name": "더라이프[0]", "No": "0", "ServiceId": "772", "Category": "여성/오락" },
      { "Name": "KBS조이[1]", "No": "1", "ServiceId": "619", "Category": "여성/오락" },

**Comment by epg2xml** [comment]
수정하였습니다. v2.3.0으로 판올림 하세요.
