### ISSUE TITLE
ERROR UTILS 40: 요청 중 에러 메세지가 나옵니다.

### ISSUE THREAD

**Issue by teamjoetv** [epg2xml/epg2xml#26]
v1때부터 너무나 애용하고 있는 유저입니다. 항상 감사하다는 말씀 전합니다.
v2로 업그레이드 진행중인데. Channels.json 초기 작성시 KT와 DAUM 채널정보를 못받아 오며, 아래와 같은 에러들을 남깁니다.

 python -m epg2xml run 

2022/11/15 09:34:38 ERROR    UTILS     40: 요청 중 에러:
Traceback (most recent call last):
  File "/home/joetv/.local/lib/python3.8/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
  File "/usr/lib/python3/dist-packages/simplejson/scanner.py", line 79, in scan_once
    return _scan_once(string, idx)
  File "/usr/lib/python3/dist-packages/simplejson/scanner.py", line 70, in _scan_once
    raise JSONDecodeError(errmsg, string, idx)
simplejson.errors.JSONDecodeError: Expecting value: line 2 column 1 (char 4)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/joetv/docker/tvheadend-klive-test/epg2xml_v2/epg2xml/epg2xml/utils.py", line 34, in request_data
    ret = r.json()
  File "/home/joetv/.local/lib/python3.8/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 2 column 1 (char 4)
2022/11/15 09:34:39 ERROR    UTILS     40: 요청 중 에러:
Traceback (most recent call last):
.
.
.
2022/11/15 09:34:55 INFO     PROV     118: [KT   ] 000 service channels successfully fetched from server.
2022/11/15 09:34:57 INFO     PROV     118: [LG   ] 350 service channels successfully fetched from server.
2022/11/15 09:34:59 INFO     PROV     118: [SK   ] 265 service channels successfully fetched from server.
.
.
.
requests.exceptions.JSONDecodeError: Expecting value: line 27 column 1 (char 26)
2022/11/15 09:35:07 INFO     PROV     118: [DAUM ] 000 service channels successfully fetched from server.
2022/11/15 09:35:14 INFO     PROV     118: [NAVER] 476 service channels successfully fetched from server.
2022/11/15 09:35:16 INFO     PROV     118: [WAVVE] 163 service channels successfully fetched from server.
2022/11/15 09:36:00 INFO     PROV     118: [TVING] 456 service channels successfully fetched from server.
2022/11/15 09:36:01 INFO     PROV     118: [SPOTV] 007 service channels successfully fetched from server.
2022/11/15 09:36:01 INFO     PROV      48: Channel file was upgraded. You may check the changes here: /home/xxx/xxx/epg2xml_v2/epg2xml/Channel.json
2022/11/15 09:36:01 INFO     MAIN      89: Writing xmltv.dtd header ...
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tv SYSTEM "xmltv.dtd">

<tv generator-info-name="epg2xml v2.4.0">
2022/11/15 09:36:01 INFO     MAIN     110: Done.
</tv>

KT와 DAUM fetch 할때만 에러가 주욱 뜨는데. 혹시 어떤 방법을 제가 시도해볼수 있는지 알려주실수 있으신가요.
환경은 우분투이고, 
Python 3.8.0
bs4 4.11.1
lxml 4.9.1
requests 2.28.1 입니다

**Comment by epg2xml** [comment]
파이썬 기본 json이 아닌 simplejson을 쓰고 계신 것 같습니다. 그걸 지우거나 `main` 브랜치에서 최신 버전을 설치해서 써보세요.
