### ISSUE TITLE
최신 버전 설치 후 htsmsg_xml_deserialize error Unknown syntatic element 오류

### ISSUE THREAD

**Issue by Taemni** [epg2xml/epg2xml#27]
안녕하세요. 항상 감사드립니다.
epg2xml을 최신 버전으로 업그레이드하니 tvheadend 로그에서 아래와 같은 오류가 발생합니다.

```
Loglevel debug: enabled
2022-11-21 09:27:42.268 xmltv: /usr/bin/tv_grab_file: grab /usr/bin/tv_grab_file
2022-11-21 09:27:42.270 spawn: Executing "/usr/bin/tv_grab_file"
2022-11-21 09:27:55.839 xmltv: /usr/bin/tv_grab_file: htsmsg_xml_deserialize error Unknown syntatic element: 
2022-11-21 09:27:55.839 xmltv: /usr/bin/tv_grab_file: grab returned no data
```

사용 환경
```
Ubuntu 18.04.4 LTS
Python 3.8.0
beautifulsoup4      4.11.1
lxml                4.9.1
epg2xml             2.5.0.dev4+g2ed1ec2
```

[2.4.0 설치 ](https://github.com/epg2xml/epg2xml/commit/da83a547cdbb28a32ddf0943bcaef4c72b52ba2a) 버전으로 설치하면 정상 작동되고요. 확인해 봐야 할 부분이 있을까요?

2.4.0 (정상 작동)
pip install "epg2xml[lxml] @ git+https://github.com/epg2xml/epg2xml.git@da83a547cdbb28a32ddf0943bcaef4c72b52ba2a"

최신 (위 오류 발생)
pip install "epg2xml[lxml] @ git+https://github.com/epg2xml/epg2xml.git@2ed1ec20564fbea3bc24f6618615e20e20c7c640"

tvheadend 버전은 `HTS Tvheadend 4.3.0~pre+202207172121-0~built202207172246~git1c65e8b0f~ubuntu18.04.1` 입니다.

**Comment by epg2xml** [comment]
v2.4.0 대비 최근 커밋을 비교 https://github.com/epg2xml/epg2xml/compare/v2.4.0...main 해보면 출력 부분에 달라진게 없습니다. (로그가 섞여 들어가는게 아니라면...)

같은 설정으로 두 버전을 사용해서 파일로 출력했을 때 차이가 나는지 난다면 어떤 부분에서 나는지 확인해주시면 저도 한번 보겠습니다.

**Comment by Taemni** [comment]
비교해봤는데 generator 말고는 차이가 없습니다.
`<tv generator-info-name="epg2xml v2.5.0.dev4+g2ed1ec2">`
`<tv generator-info-name="epg2xml v2.4.0">`

제가 사용하는 클라우드 서버 인스턴스 두 개에서 테스트 해봤는데 tvheadend 로그에서 같은 문제가 발생합니다. (2.4.0은 정상)
터미널에서 커맨드를 썼을 때 xml 파일 정상적으로 생성되고 --sockxml을 사용해도 tvheadend에서 확인해 보면 업데이트가 됩니다.
tvheadend 크론으로 내부 XMLTV: tv_grab_file을 실행하거나 내부 EPG 그래버 다시 실행을 눌렀을 때만 위 에러가 발생합니다.

**Comment by epg2xml** [comment]
로깅 관련 수정하다가 버그를 만들었네요. 수정했으니 사용해보세요. 제보 고맙습니다!

**Comment by Taemni** [comment]
> 로깅 관련 수정하다가 버그를 만들었네요. 수정했으니 사용해보세요. 제보 고맙습니다!

정상 작동합니다. 감사합니다.
