### ISSUE TITLE
Daum 제공자가 동작하지 않습니다.

### ISSUE THREAD

**Issue by shfactory** [epg2xml/epg2xml#3]
daum.py 에서
30,33번줄의 `svc_cate` 를 `cate` 로 수정해야 될것 같습니다.

**Comment by wiserain** [comment]
현재 코드로 잘 동작하는데 어떤 부분이 문제인가요?

**Comment by shfactory** [comment]
채널목록을 새로불러올때 다음 제공자에서 에러가 납니다.

**Comment by shfactory** [comment]
ERROR    PROV     121: [DAUM ] Unsupported or invalid CSS selector: "div[class=layer_tv"

**Comment by wiserain** [comment]
적어주신 로그는 daum.py의 27라인이네요 svc_cate나 cate는 관련 없을것 같은데... 다음 페이지 검색이 막히지 않았는지 한번 점검해 보세요.

**Comment by shfactory** [comment]
<div id="channelNaviLayer" class="tab_sub">
        <div class="wrap_sub"> 
            <span class="cate ">...</span>

다음 페이지가 이렇게 바껴있습니다.

**Comment by wiserain** [comment]
l30,33의 svc_cate는 변수명일 뿐이고 html 파싱에 쓰지 않습니다. class 명이 cate든 abc든 상관없습니다. 정 못 미더우시면 말씀하신대로 수정하고 되는지 알려주세요.

**Comment by shfactory** [comment]
수정 후 동작 잘됩니다. 제가 잘몰라서 죄송합니다ㅜ

**Comment by wiserain** [comment]
수정 해야만 동작한다는건가요? 아님 그대로의 코드로도 문제없다는건가요?

**Comment by shfactory** [comment]
수정하니 오류없이 Channel.json 파일이 생성됩니다.

**Comment by shfactory** [comment]
다시 수정전으로 바꿔봤는데 작동하네요 제 기기에 문제가 있었나봅니다. 괜한 질문 올려서 죄송합니다

**Comment by shfactory** [comment]
수정전껄로 다시봐꿔봤는데 잘됩니다. 제 기기에 문제가 있었던것 같습니다. 괜한 질문 올려서 죄송합니다

**Comment by wiserain** [comment]
넵 그래도 다행이네요. 계속 찜찜할뻔 했습니다.
