### ISSUE TITLE
실행 중 에러로 비정상 종료 - string indices must be integers, not 'str'

### ISSUE THREAD

**Issue by iykkim** [epg2xml/epg2xml#34]
안녕하세요.
먼저 좋은 유틸 제작해 주셔서 감사드리며, 사용 중 문제가 발생해서 문의 드립니다.
계속 잘 사용하고 있었는데, 오늘 저녁 실행 중에 갑자기 다음과 같이 에러가 나오고 비정상 종료가 되고 있습니다.

2023/09/24 19:20:39 INFO     PROV     118: [KT   ] 244 service channels successfully fetched from server.
2023/09/24 19:20:41 ERROR    PROV     120: [LG   ] Exception while retrieving service channels:
Traceback (most recent call last):
  File "/home/hts/.hts/tvheadend/epg2xml/epg2xml/providers/__init__.py", line 117, in load_svc_channels
    self.get_svc_channels()
  File "/home/hts/.hts/tvheadend/epg2xml/epg2xml/providers/lg.py", line 47, in get_svc_channels
    cate = {x["urcBrdCntrTvChnlGnreCd"]: x["urcBrdCntrTvChnlGnreNm"] for x in data["brdGnreDtoList"]}
                                                                              ~~~~^^^^^^^^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'

정확히는 모르겠지만 아마도 LG EPG 사이트 구조가 변경되어서 발생하는 문제가 아닌지 싶습니다.
LG 사이트의 채널 장르 번호 부분이 바뀌어서 숫자가 아닌 문자열로 대체된거 같은데 확인이 필요해 보입니다.

도움에 미리 감사드립니다.

**Comment by Taemni** [comment]
L사의 전산 시스템 개편으로 인해 2023년 9월 22일(금) 오후 10시 ~ 25일(월)오전 8시까지 웹 서비스가 일시 중지되어 에러가 발생하는 것으로 보입니다. 

![image](https://github.com/epg2xml/epg2xml/assets/48712000/bd377105-bd97-4ee9-996a-2642e14974dc)

**Comment by iykkim** [comment]
아 그렇군요.
매우 빠른 답변 감사합니다. ^^
작업이 종료된 후에 확인해 보면 되겠네요, 혹시 계속 문제가 있으면 새로 문의글 작성해서 여쭤보겠습니다.
