### ISSUE TITLE
spotv 제공자에서 xml 생성오류 (24:00)

### ISSUE THREAD

**Issue by myepg** [epg2xml/epg2xml#35]
spotv 제공자에서 xml 생성 할때  

2023-09-30 24:00

시간이 24:00 인 경우 오류가 있습니다 

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2023-09-30 24:00' does not match format '%Y-%m-%d %H:%M'

24:00 를 00:00 으로 임시로 수정해서 동작하는건 확인했습니다 
epg2xml/providers/spotv.py
68라인

                _prog.stime = datetime.strptime(p["startTime"].replace('24:00', '00:00'), "%Y-%m-%d %H:%M")
                if p["endTime"]:
                    _prog.etime = datetime.strptime(p["endTime"].replace('24:00', '00:00'), "%Y-%m-%d %H:%M")

좋은 프로그램 잘 사용하고 있습니다.
감사합니다

**Comment by epg2xml** [comment]
수정했습니다. 아시안게임 관련 채널이 추가되면서 없던 문제가 생긴것 같네요. 알려주셔서 고맙습니다.
