### ISSUE TITLE
spotv epg 정보 없는 채널이 있는 경우 저장 오류

### ISSUE THREAD

**Issue by myepg** [epg2xml/epg2xml#39]
안녕하세요. 

spotv 에서 epg 정보가 없는 채널(이번 경우는 TV조선, NBA TV)이 있을 경우 
남은 채널을 처리하지 못하고 빠져나가는거 같습니다. 

2023/10/04 05:10:18 INFO     PROV     124: [KT   ] 241 service channels loaded from cache.
2023/10/04 05:10:18 INFO     PROV     124: [LG   ] 353 service channels loaded from cache.
2023/10/04 05:10:18 INFO     PROV     124: [SK   ] 272 service channels loaded from cache.
2023/10/04 05:10:18 INFO     PROV     124: [DAUM ] 392 service channels loaded from cache.
2023/10/04 05:10:18 INFO     PROV     124: [NAVER] 472 service channels loaded from cache.
2023/10/04 05:10:18 INFO     PROV     124: [WAVVE] 155 service channels loaded from cache.
2023/10/04 05:10:18 INFO     PROV     124: [TVING] 258 service channels loaded from cache.
2023/10/04 05:10:18 INFO     PROV     124: [SPOTV] 012 service channels loaded from cache.
2023/10/04 05:10:18 INFO     PROV     163: [SPOTV] 요청 12 - 불가 0 = 최종 12
2023/10/04 05:10:18 INFO     MAIN      72: Writing xmltv.dtd header ...
2023/10/04 05:10:21 INFO     SPOTV     66: 001/012 MBC <17.spotv>
2023/10/04 05:10:21 INFO     SPOTV     66: 002/012 KBS1 <18.spotv>
2023/10/04 05:10:21 INFO     SPOTV     66: 003/012 KBS2 <19.spotv>
2023/10/04 05:10:21 INFO     SPOTV     66: 004/012 SBS <16.spotv>
2023/10/04 05:10:21 INFO     SPOTV     66: 005/012 TV조선 <20.spotv>
2023/10/04 05:10:21 WARNING  SPOTV     69: EPG 정보가 없거나 없는 채널입니다: TV조선 <20.spotv>
2023/10/04 05:10:21 INFO     MAIN      93: Done.

epg2xml/providers/spotv.py
71라인 
아래는 임시로 continue 넣고 실행 해본 로그입니다.

            if not programs:
                log.warning("EPG 정보가 없거나 없는 채널입니다: %s", _ch)
                # 오늘 없으면 내일도 없는 채널로 간주
                # break
                continue

2023/10/04 05:10:49 INFO     PROV     124: [KT   ] 241 service channels loaded from cache.
2023/10/04 05:10:49 INFO     PROV     124: [LG   ] 353 service channels loaded from cache.
2023/10/04 05:10:49 INFO     PROV     124: [SK   ] 272 service channels loaded from cache.
2023/10/04 05:10:49 INFO     PROV     124: [DAUM ] 392 service channels loaded from cache.
2023/10/04 05:10:49 INFO     PROV     124: [NAVER] 472 service channels loaded from cache.
2023/10/04 05:10:49 INFO     PROV     124: [WAVVE] 155 service channels loaded from cache.
2023/10/04 05:10:49 INFO     PROV     124: [TVING] 258 service channels loaded from cache.
2023/10/04 05:10:49 INFO     PROV     124: [SPOTV] 012 service channels loaded from cache.
2023/10/04 05:10:49 INFO     PROV     163: [SPOTV] 요청 12 - 불가 0 = 최종 12
2023/10/04 05:10:49 INFO     MAIN      72: Writing xmltv.dtd header ...
2023/10/04 05:10:51 INFO     SPOTV     66: 001/012 MBC <17.spotv>
2023/10/04 05:10:51 INFO     SPOTV     66: 002/012 KBS1 <18.spotv>
2023/10/04 05:10:51 INFO     SPOTV     66: 003/012 KBS2 <19.spotv>
2023/10/04 05:10:51 INFO     SPOTV     66: 004/012 SBS <16.spotv>
2023/10/04 05:10:51 INFO     SPOTV     66: 005/012 TV조선 <20.spotv>
2023/10/04 05:10:51 WARNING  SPOTV     69: EPG 정보가 없거나 없는 채널입니다: TV조선 <20.spotv>
2023/10/04 05:10:51 INFO     SPOTV     66: 006/012 SPOTV <9.spotv>
2023/10/04 05:10:51 INFO     SPOTV     66: 007/012 SPOTV2 <10.spotv>
2023/10/04 05:10:51 INFO     SPOTV     66: 008/012 SPOTV PRIME <15.spotv>
2023/10/04 05:10:51 INFO     SPOTV     66: 009/012 SPOTV Golf & Health <11.spotv>
2023/10/04 05:10:51 INFO     SPOTV     66: 010/012 SPOTV ON <1.spotv>
2023/10/04 05:10:51 INFO     SPOTV     66: 011/012 SPOTV ON2 <2.spotv>
2023/10/04 05:10:51 INFO     SPOTV     66: 012/012 NBA TV <3.spotv>
2023/10/04 05:10:51 WARNING  SPOTV     69: EPG 정보가 없거나 없는 채널입니다: NBA TV <3.spotv>
2023/10/04 05:10:51 INFO     MAIN      93: Done.

감사합니다.

**Comment by epg2xml** [comment]
중요한 버그네요. 제보 고맙습니다.
