### ISSUE TITLE
EPG Title 뒤에 공백 1개 들어가는 문제

### ISSUE THREAD

**Issue by Taemni** [epg2xml/epg2xml#48]
안녕하세요. 어느 날부터 녹화가 정상적으로 진행되지 않아 문제를 확인했습니다.

tvheadend에서 자동 녹화 시 예를 들어 `아는 형님` 방송을 녹화한다면 정규식 부분에 `아는\s형님\s?\(\d+회\)$`를 넣고 녹화를 했었습니다. (재방송이나 스페셜 방송은 뒤에 (재) or 스페셜이 붙기 때문에 제외하려고 $를 사용했습니다.)

다가오는 녹화 목록에 보이지 않는 방송들이 생겨 확인해 보니 EPG Title 뒤에 공백 한 개씩 들어가 있어서 녹화가 진행이 안 되었습니다.

예약된 녹화의 제목을 확인해 보면 전부 아래와 같이 제목 뒤에 공백 1개씩 들어가 있습니다.
![image](https://github.com/epg2xml/epg2xml/assets/48712000/abedf7d6-55cd-4e9d-9940-9443df6cfadb)

정확히 언제부터 발생했는지는 모르겠습니다만, 이 부분 수정해 주실 수 있으실까요?
이 부분이 신경 안 쓰이시는 분들도 계시겠지만, 수정하여 배포가 어려우시다면 수정해야 하는 부분을 알려주시면 감사하겠습니다.

감사합니다.

추가)
사용하고 있는 제공자는 L, Daum입니다. 다른 제공자는 확인해 보지 못했습니다.
설치된 버전
epg2xml @ git+https://github.com/epg2xml/epg2xml.git@40e3667358a8931e1876bbae87f8958e67ad8511

xmltv.xml 파일을 열어보니 재방송일 경우 (재) 뒤에는 공백이 붙지 않지만, 본방송만 뒤에 공백 1개가 추가되네요.

**Comment by epg2xml** [comment]
점검해보겠습니다.

**Comment by epg2xml** [comment]
수정 하였습니다.

**Comment by Taemni** [comment]
> 수정 하였습니다.

정상 작동합니다. 감사합니다.
