### ISSUE TITLE
ServiceId를 찾지 못합니다...

### ISSUE THREAD

**Issue by kjs3374** [epg2xml/epg2xml#5]
2021/08/15 18:07:55 WARNING  PROV     142: [KT   ] 'ServiceId' Not Found: 1
2021/08/15 18:07:55 WARNING  PROV     142: [KT   ] 'ServiceId' Not Found: 2
2021/08/15 18:07:55 WARNING  PROV     142: [KT   ] 'ServiceId' Not Found: 3
2021/08/15 18:07:55 INFO     PROV     162: [KT   ] 요청 3 - 불가 3 = 최종 0
2021/08/15 18:07:55 INFO     MAIN      99: Writing xmltv.dtd header ...

output 내용입니다.

{
  "GLOBAL": {
    "ENABLED": true,
    "FETCH_LIMIT": 2,
    "ID_FORMAT": "{ServiceId}.{Source.lower()}",
    "ADD_REBROADCAST_TO_TITLE": false,
    "ADD_EPNUM_TO_TITLE": true,
    "ADD_DESCRIPTION": true,
    "ADD_XMLTV_NS": false,
    "GET_MORE_DETAILS": false
  },
  "KT": {
    "MY_CHANNELS": ["1","2","3"]
  },

epg2xml 내용입니다.

MY_CHANNELS 에 서비스 아이디를 입력해도 ServiceId를 못찾아 검색이 되지않습니다.
epg2xml.json 입력방식이 잘못된것인지에 대한 내용을 찾기 어려워 문의드립니다.

**Comment by epg2xml** [comment]
`MY_CHANNELS`의 내용은 아래와 같이 `Channel.json`의 `CHANNELS` 항목을 가져다 쓰시면 됩니다.

```json
"MY_CHANNELS": [
    { "Name": "NQQ", "No": "0", "ServiceId": "0" }
]
```
