### ISSUE TITLE
Icon_url 비활성화 방법

### ISSUE THREAD

**Issue by wowwoo** [epg2xml/epg2xml#6]
안녕하세요

새로운 버전이 올라와서 사용해봤는데
전보다 더 간편해진 것 같은 느낌이 듭니다
채널 ID를 확인하느라 애쓸 것도 없어지고
레퍼런스가 주어지니 알아서 편집해서 사용하기
좋더라구요

근데 epg2xml.json을 채널에 따라 편집을 했는데
웨이브와 티빙의 경우에는 Icon_url이 붙더라구요
저는 개인적으로 사용하는 채널 로고가 있어서
M3U 플레이리스트에 적용해서 사용하는데,
혹시 XML 파일에 Icon_url 태그가 붙지 않도록
하는 옵션이 있나요?

제가 혼자 해결해보려고
provider 폴더의 웨이브와 티빙 파이썬 스크립트에서
Icon_url을 붙여주는 것 같은 문항들을 삭제했는데도
계속 붙습니다

제 능력 외인 것 같아요

항상 잘 쓰고 있습니다 감사합니다

**Comment by epg2xml** [comment]
후기 감사합니다. 

`ADD_CHANNEL_ICON` 옵션을 추가했으니 테스트 해보시기 바랍니다. https://github.com/epg2xml/epg2xml/commit/1acac3401c18a8af5954f82349f551880421f66c

**Comment by wowwoo** [comment]
와 정말 감사합니다
이렇게 빠른 시간 내 반영해 주시다니... ㅠㅜ
정말 잘 작동합니다!

감사합니다
