### ISSUE TITLE
Daum 제공자 파싱 오류

### ISSUE THREAD

**Issue by Taemni** [epg2xml/epg2xml#60]
```
python 버전 3.8
epg2xml 버전 https://github.com/epg2xml/epg2xml/commit/bd547f6dbdec14420c26fd95a3452d9d4a31d060
```
LG와 Daum을 사용 중인데 Daum 제공자에서 에러가 발생하고 있습니다.
IP 차단 상태는 아닙니다. curl로 확인했습니다. 확인 부탁드립니다.
언제나 감사드립니다.

```shell
root@server2:/home/hts# python3 -m epg2xml run
2024/03/01 21:22:50 INFO     PROV     294: [DAUM ] 390 service channels loaded from cache
2024/03/01 21:22:50 INFO     PROV     344: [DAUM ] 요청   4 - 불가   0 = 최종   4
2024/03/01 21:22:50 INFO     DAUM      56: 001/004 KBS2 <지상파 KBS2.daum>
2024/03/01 21:22:51 ERROR    DAUM      64: 프로그램 파싱 중 예외: KBS2 <지상파 KBS2.daum>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/epg2xml/providers/daum.py", line 60, in get_programs
    _epgs = self.__epgs_of_days(_ch.id, data)
  File "/usr/local/lib/python3.8/dist-packages/epg2xml/providers/daum.py", line 75, in __epgs_of_days
    basedate = datetime.strptime(days[0].text.strip(), "%m.%d").replace(year=currdate.year)
  File "/usr/lib/python3.8/_strptime.py", line 579, in _strptime_datetime
    return cls(*args)
ValueError: day is out of range for month
```

**Comment by epg2xml** [comment]
안녕하세요.

DAUM 제공자 kbs2 해봤는데 테스트 해봤는데 잘 됩니다. 결과가 보이실지 모르겠지만 github action으로 테스트 돌려도 문제가 없네요. https://github.com/epg2xml/epg2xml/actions/runs/8114412551

다른 문제가 없는지 한번만 다시 체크해주세요.

**Comment by Taemni** [comment]
> 안녕하세요.
> 
> DAUM 제공자 kbs2 해봤는데 테스트 해봤는데 잘 됩니다. 결과가 보이실지 모르겠지만 github action으로 테스트 돌려도 문제가 없네요. https://github.com/epg2xml/epg2xml/actions/runs/8114412551
> 
> 다른 문제가 없는지 한번만 다시 체크해주세요.

지금은 또 잘 되네요. 디버깅 로그 켜고, 에러 다시 발생하는지 확인해 보겠습니다.

**Comment by Taemni** [comment]
며칠 지켜봤지만 지금은 정상 작동하고 하고 있습니다. 디버깅 로그를 꺼놔서 언제부터 오류가 발생했는지는 모르겠네요. 2월 말 29일 ~ 3월 1일 사이 월말 월초 넘어가면서 발생한 것 같기도 하고.. 지금은 정상 작동하기 때문에 Close 하겠습니다.
