### ISSUE TITLE
LG 채널 오류

### ISSUE THREAD

**Issue by iykkim** [epg2xml/epg2xml#62]
안녕하세요.
어제 부터 LG epg 채널 업데이트 시 다음과 같이 오류가 나고 있어서 확인이 필요해 보입니다.
업데이트 한 2.5.1에서도 같습니다.

2024/06/01 16:47:43 INFO     PROV     118: [KT
  ] 241 service channels successfully fetched from server.
2024/06/01 16:47:45 ERROR    PROV     120: [LG
  ] Exception while retrieving service channels:
Traceback (most recent call last):
  File "/home/hts/.hts/tvheadend/epg2xml/epg2xml/providers/__init__.py", line 117, in load_svc_channels
    self.get_svc_channels()
  File "/home/hts/.hts/tvheadend/epg2xml/epg2xml/providers/lg.py", line 54, in get_svc_channels
    "Category": cate[ch["urcBrdCntrTvChnlGnreCd"]],
                ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: '09'

**Comment by Taemni** [comment]
최신 버전으로 설치하셨으면 경로에 Channel.json 파일 삭제 후 다시 한 번 실행해보세요

**Comment by iykkim** [comment]
삭제 후 다시 실행해 봐도 동일합니다.
Channel.json 파일 생성이 안 되고 위와 같은 에러가 나오면서 종료됩니다.

**Comment by iykkim** [comment]
이 내용 역시 이전과 유사하게 예외 처리 먼저 하시면 어떨까 합니다.
여러 사이트 EPG 정보를 가져오는 단계에서 특정 사이트 의 오류 발생시 종료되지 않고 다음 사이트로 진행하면 EPG 생성은 가능하고 이러한 오류는 에러 로그 파일 생성하도록 해서 사용자가 문의시 확인 후 시간 여유를 가지시고   수정하시면 좋을거 같아서 의견을 드려봤습니다.

**Comment by epg2xml** [comment]
아직 LG 제공자 안되나요?



> 이 내용 역시 이전과 유사하게 예외 처리 먼저 하시면 어떨까 합니다. 여러 사이트 EPG 정보를 가져오는 단계에서 특정 사이트 의 오류 발생시 종료되지 않고 다음 사이트로 진행하면 EPG 생성은 가능하고 이러한 오류는 에러 로그 파일 생성하도록 해서 사용자가 문의시 확인 후 시간 여유를 가지시고 수정하시면 좋을거 같아서 의견을 드려봤습니다.

이 부분은 고려하겠습니다.

**Comment by iykkim** [comment]
네, 아침에도 해봤는데 동일한 에러가 LG epg에서 나온 후 종료되고 있어서 계속 EPG 생성을 못하고 있습니다.

**Comment by Taemni** [comment]
저는 최신 커밋 버전으로 설치 후 정상 작동하는데 이상하네요.

**Comment by epg2xml** [comment]
수정 이후로 잘 되는데 어떤 에러인가요?

**Comment by iykkim** [comment]
2024/06/01 16:47:43 INFO PROV 118: [KT
] 241 service channels successfully fetched from server.
2024/06/01 16:47:45 ERROR PROV 120: [LG
] Exception while retrieving service channels:
Traceback (most recent call last):
File "/home/hts/.hts/tvheadend/epg2xml/epg2xml/providers/init.py", line 117, in load_svc_channels
self.get_svc_channels()
File "/home/hts/.hts/tvheadend/epg2xml/epg2xml/providers/lg.py", line 54, in get_svc_channels
"Category": cate[ch["urcBrdCntrTvChnlGnreCd"]],
~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: '09'

위에 처음 첨부한 에러입니다.

사용하는 기종은 안드로이드 TV box인데 사정이 있어 원격 작업 중이라서 커널 업데이트 패키지가 있는지 확인이 안되고, 있다고 해도 원격으로 설치할 수가 없는 상황이라서 난감합니다..

업데이트 한건 epg2xml만이고 변경된게 아무 것도 없었는데 1일 부터 갑자기 나타난 문제입니다.

**Comment by iykkim** [comment]
2024/06/06 09:37:29 INFO     PROV     118: [KT
  ] 241 service channels successfully fetched from server.
2024/06/06 09:37:34 ERROR    PROV     120: [LG
  ] Exception while retrieving service channels:
Traceback (most recent call last):
  File "/home/hts/.hts/tvheadend/epg2xml/epg2xml/providers/__init__.py", line 117, in load_svc_channels
    self.get_svc_channels()
  File "/home/hts/.hts/tvheadend/epg2xml/epg2xml/providers/lg.py", line 54, in get_svc_channels
    "Category": cate[ch["urcBrdCntrTvChnlGnreCd"]],
                ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: '09'

아직도 여전히 에러 상태여서 참고로 실행 중지 내용 또 첨부합니다.

**Comment by epg2xml** [comment]
여전히 문제없이 실행됩니다. 최신 버전을 사용하는지 다시 한번 확인해보시고 그래도 여전하다면 다른 분들의 도움을 기다려야할 것 같습니다.

**Comment by iykkim** [comment]
root@AOL-Debian:~# epg2xml -v
epg2xml v2.5.1

버전은 위와 같이 최신입니다.

업데이트 전인 1일경 아무 변경도 없었는데 갑자기 이 문제가 발생했었고 2.5.1 업데이트 후에도 동일합니다.
아래는 방금 실행한 모습으로 여전히 안 되고 있습니다.
현재로서는 예외처리 기능 추가를 완료해 주시면 좋겠습니다.

2024/06/07 05:42:03 INFO     PROV     118: [KT
  ] 241 service channels successfully fetched from server.
2024/06/07 05:42:06 ERROR    PROV     120: [LG
  ] Exception while retrieving service channels:
Traceback (most recent call last):
  File "/home/hts/.hts/tvheadend/epg2xml/epg2xml/providers/__init__.py", line 117, in load_svc_channels
    self.get_svc_channels()
  File "/home/hts/.hts/tvheadend/epg2xml/epg2xml/providers/lg.py", line 54, in get_svc_channels
    "Category": cate[ch["urcBrdCntrTvChnlGnreCd"]],
                ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: '09'

**Comment by epg2xml** [comment]
예외처리는 지금 당장 들여다 볼 수가 없습니다. 일단 epg2xml.json 설정 파일에서 LG 관련 채널 설정을 빼서 사용하고 계시길 바랍니다. `enabled: false` 하면 될겁니다.

**Comment by iykkim** [comment]
말씀하신데로 옵션 추가해서 EPG  생성 다시 되고 있습니다.
감사합니다.

**Comment by epg2xml** [comment]
일단은 문제가 없는 것 같아서 닫겠습니다. 문제가 발생하면 새로운 이슈를 열어주세요.
